### ISSUE TITLE
1.10 Support!

### ISSUE THREAD

**Issue by ThomasIO** [sultanskyman/WildSex#7]
Update to 1.10! Server owner's like myself admire this plugin!

**Comment by DrkMatr1984** [comment]
Coming soon! I need to update it for myself also. :) Expect an update in the next week.

**Comment by sultanskyman** [comment]
@ThomasIO , the update supporting MC 1.10.2 and 1.11 is now ready as WildSex 4, you can get it in the releases tab. It is also awaiting BukkitDev approval. Despite the huge delay, I hope this is useful :)

**Comment by DrkMatr1984** [comment]
Thank you sultan! I will upload to spigot and sync our repos immediately
