### ISSUE TITLE
1.12 release

### ISSUE THREAD

**Issue by aolko** [sultanskyman/WildSex#9]
how about 1.12.* release?

**Comment by DrkMatr1984** [comment]
I can get it done by end of this week :) no one else has asked.

**Comment by aolko** [comment]
yay, i'm first to ask :)

**Comment by DrkMatr1984** [comment]
@skyman Are you okay if I update the nms modules for Wildsex and release a compatibility update? Since you've returned to the project I've been trying to tread lightly on your code base so I don't screw anything up you had going on :P

**Comment by cgokmen** [comment]
Unfortunately college has taken its toll on all my will to work on these
pet projects, so my plans for this are sort of shelved for now, and if I do
get to it, I should be able to merge just fine later - so feel free to go
ahead and update, and thanks for asking!

**Comment by aolko** [comment]
so i guess that's fail

**Comment by DrkMatr1984** [comment]
Yeah for now, I have some side projects I'm working on also, plus I'm a 33-year old family man with a baby and 7 year old son :P I do plan to update this plugin sooner or later, I'm just busy atm with xmas, overtime, and children.

**Comment by DrkMatr1984** [comment]
I'm working on this tonight, probably have an update by the morning.

**Comment by DrkMatr1984** [comment]
https://dev.bukkit.org/projects/wildsex
https://www.spigotmc.org/resources/wildsex.14129/
